[build]
publish = "public"
command = "npm run build && ls -l public/static/gatsby-image-originals/**/*"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[plugins]]
package = "../../plugin/src/index.ts"
