[functions.gatsby-image]
external_node_modules = ["electron", "keyv", "mozjpeg", "pngquant-bin"]
included_files = [".cache/caches/gatsby-runner/**/*.json"]

[[ plugins ]]
package = "@netlify/plugin-gatsby"